filenames:
  litigious_flnm: litigious_words.txt
  complex_flnm: complexity_words.txt
  uncertianity_flnm: uncertainty_words.txt
  syllable_flnm: syllable_count.txt
  vocab_pos_flnm: vocab_pos.txt
  vocab_neg_flnm: vocab_neg.txt
  contraction_flnm: contraction_words.txt
  stop_words_flnm: StopWords_Full_list.txt
  negate_words_flnm: negated_words.txt
