# configs/preprocessing/preprocessing.yaml

preprocessing:
  additional_stop_words:
    - "bottom"
    - "Bottom"
    - "top"
    - "Top"
    - "call"
  cleanup_phrases:
  - "Thank you"
  - "thank you"
  - "thanks"
  - "Thanks"
  - "earnings call"
  - "earnings release"
  - "earnings conference"
  greeting_phrases: ["good morning", "good afternoon", "good evening"]

psycholinguistics:
  filt_sections:
  - FILT_MD
  - FILT_QA
  - FILT_CEO_MD
  - FILT_CEO_QA
  - FILT_EXEC_MD
  - FILT_EXEC_QA
  - FILT_ANL_QA
