# access attirbutes example: config.lib_config.word2vec_unigram
defaults:
  - lib_config/snowflake
  - lib_config/dask
  - lib_config/word2vec
  - lib_config/preprocessing
  - lib_config/blob_conf
  - lib_config/paths